notifications:
  email: false
language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install .
  - pip install coverage codecov
script:
  - tests/tests.sh
  - nosetests -c .noserc
after_success:
  - codecov
